# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlpipeline.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlpipeline.proto',
  package='mlpipeline',
  syntax='proto3',
  serialized_options=b'\n\023io.grpc.examples.mlB\007MLProtoP\001\242\002\002ML',
  serialized_pb=b'\n\x10mlpipeline.proto\x12\nmlpipeline\"o\n\x08RawEvent\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x03\x12\x0f\n\x07sensor1\x18\x03 \x01(\x02\x12\x0f\n\x07sensor2\x18\x04 \x01(\x02\x12\x0f\n\x07sensor3\x18\x05 \x01(\x02\x12\x0f\n\x07sensor4\x18\x06 \x01(\x02\"F\n\x0cRawEventList\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12#\n\x05\x65vent\x18\x02 \x03(\x0b\x32\x14.mlpipeline.RawEvent\"&\n\x07\x46\x65\x61ture\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"F\n\x0b\x46\x65\x61tureList\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12$\n\x07\x66\x65\x61ture\x18\x02 \x03(\x0b\x32\x13.mlpipeline.Feature\"\x92\x01\n\nPrediction\x12\x0f\n\x07modelId\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65viceId\x18\x02 \x01(\t\x12\x32\n\x06result\x18\x03 \x03(\x0b\x32\".mlpipeline.Prediction.ResultEntry\x1a-\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x64\n\x19\x46\x65\x61tureEngineeringService\x12G\n\x10\x65ngineerFeatures\x12\x18.mlpipeline.RawEventList\x1a\x17.mlpipeline.FeatureList\"\x00\x32Q\n\x11PredictionService\x12<\n\x07predict\x12\x17.mlpipeline.FeatureList\x1a\x16.mlpipeline.Prediction\"\x00\x42%\n\x13io.grpc.examples.mlB\x07MLProtoP\x01\xa2\x02\x02MLb\x06proto3'
)




_RAWEVENT = _descriptor.Descriptor(
  name='RawEvent',
  full_name='mlpipeline.RawEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='mlpipeline.RawEvent.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='mlpipeline.RawEvent.time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor1', full_name='mlpipeline.RawEvent.sensor1', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor2', full_name='mlpipeline.RawEvent.sensor2', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor3', full_name='mlpipeline.RawEvent.sensor3', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor4', full_name='mlpipeline.RawEvent.sensor4', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=143,
)


_RAWEVENTLIST = _descriptor.Descriptor(
  name='RawEventList',
  full_name='mlpipeline.RawEventList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='mlpipeline.RawEventList.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='mlpipeline.RawEventList.event', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=215,
)


_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='mlpipeline.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mlpipeline.Feature.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mlpipeline.Feature.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=255,
)


_FEATURELIST = _descriptor.Descriptor(
  name='FeatureList',
  full_name='mlpipeline.FeatureList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='mlpipeline.FeatureList.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature', full_name='mlpipeline.FeatureList.feature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=327,
)


_PREDICTION_RESULTENTRY = _descriptor.Descriptor(
  name='ResultEntry',
  full_name='mlpipeline.Prediction.ResultEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mlpipeline.Prediction.ResultEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mlpipeline.Prediction.ResultEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=476,
)

_PREDICTION = _descriptor.Descriptor(
  name='Prediction',
  full_name='mlpipeline.Prediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelId', full_name='mlpipeline.Prediction.modelId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='mlpipeline.Prediction.deviceId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='mlpipeline.Prediction.result', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PREDICTION_RESULTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=476,
)

_RAWEVENTLIST.fields_by_name['event'].message_type = _RAWEVENT
_FEATURELIST.fields_by_name['feature'].message_type = _FEATURE
_PREDICTION_RESULTENTRY.containing_type = _PREDICTION
_PREDICTION.fields_by_name['result'].message_type = _PREDICTION_RESULTENTRY
DESCRIPTOR.message_types_by_name['RawEvent'] = _RAWEVENT
DESCRIPTOR.message_types_by_name['RawEventList'] = _RAWEVENTLIST
DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
DESCRIPTOR.message_types_by_name['FeatureList'] = _FEATURELIST
DESCRIPTOR.message_types_by_name['Prediction'] = _PREDICTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RawEvent = _reflection.GeneratedProtocolMessageType('RawEvent', (_message.Message,), {
  'DESCRIPTOR' : _RAWEVENT,
  '__module__' : 'mlpipeline_pb2'
  # @@protoc_insertion_point(class_scope:mlpipeline.RawEvent)
  })
_sym_db.RegisterMessage(RawEvent)

RawEventList = _reflection.GeneratedProtocolMessageType('RawEventList', (_message.Message,), {
  'DESCRIPTOR' : _RAWEVENTLIST,
  '__module__' : 'mlpipeline_pb2'
  # @@protoc_insertion_point(class_scope:mlpipeline.RawEventList)
  })
_sym_db.RegisterMessage(RawEventList)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), {
  'DESCRIPTOR' : _FEATURE,
  '__module__' : 'mlpipeline_pb2'
  # @@protoc_insertion_point(class_scope:mlpipeline.Feature)
  })
_sym_db.RegisterMessage(Feature)

FeatureList = _reflection.GeneratedProtocolMessageType('FeatureList', (_message.Message,), {
  'DESCRIPTOR' : _FEATURELIST,
  '__module__' : 'mlpipeline_pb2'
  # @@protoc_insertion_point(class_scope:mlpipeline.FeatureList)
  })
_sym_db.RegisterMessage(FeatureList)

Prediction = _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), {

  'ResultEntry' : _reflection.GeneratedProtocolMessageType('ResultEntry', (_message.Message,), {
    'DESCRIPTOR' : _PREDICTION_RESULTENTRY,
    '__module__' : 'mlpipeline_pb2'
    # @@protoc_insertion_point(class_scope:mlpipeline.Prediction.ResultEntry)
    })
  ,
  'DESCRIPTOR' : _PREDICTION,
  '__module__' : 'mlpipeline_pb2'
  # @@protoc_insertion_point(class_scope:mlpipeline.Prediction)
  })
_sym_db.RegisterMessage(Prediction)
_sym_db.RegisterMessage(Prediction.ResultEntry)


DESCRIPTOR._options = None
_PREDICTION_RESULTENTRY._options = None

_FEATUREENGINEERINGSERVICE = _descriptor.ServiceDescriptor(
  name='FeatureEngineeringService',
  full_name='mlpipeline.FeatureEngineeringService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=478,
  serialized_end=578,
  methods=[
  _descriptor.MethodDescriptor(
    name='engineerFeatures',
    full_name='mlpipeline.FeatureEngineeringService.engineerFeatures',
    index=0,
    containing_service=None,
    input_type=_RAWEVENTLIST,
    output_type=_FEATURELIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEATUREENGINEERINGSERVICE)

DESCRIPTOR.services_by_name['FeatureEngineeringService'] = _FEATUREENGINEERINGSERVICE


_PREDICTIONSERVICE = _descriptor.ServiceDescriptor(
  name='PredictionService',
  full_name='mlpipeline.PredictionService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=580,
  serialized_end=661,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='mlpipeline.PredictionService.predict',
    index=0,
    containing_service=None,
    input_type=_FEATURELIST,
    output_type=_PREDICTION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICTIONSERVICE)

DESCRIPTOR.services_by_name['PredictionService'] = _PREDICTIONSERVICE

# @@protoc_insertion_point(module_scope)
